version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app/data:/app/app/data
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend

  celery-worker:
    build: .
    container_name: celery-worker
    command: celery -A app.worker worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - backend

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555"
    command: flower --broker=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
